#!/bin/sh

set -e
WORKING_DIR=$PWD

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"

# you need the || true because the set -e option aborts the script if any
# command returns anything other than 0.
if [ ! -d "$HOME/.local/bin" ]; then
	mkdir "$HOME/.local" || true
	mkdir "$HOME/.local/bin" || true
fi

cd $HOME/.local/bin
ln -s "$WORKING_DIR/scripts" scripts 

# move into each directory and execute the setup script inside

for i in vim w3m newsboat; do
	cd $i && ./setup
	cd -
done
