#!/bin/sh

set -e

if [ -z "$(command -v vim)" ]; then
	echo "Vim is not installed."
	exit 1
fi

#if [ ! -d "$HOME/.vim/autoload" ]; then
#	mkdir -p "$HOME/.vim/autoload"
#	mkdir -p "$HOME/.vim/tmp"
#fi

if [ ! -d "$HOME/.cache/vim" ]; then
  mkdir -p "$HOME/.cache/vim"
fi

ln -sf "$PWD/vimrc" "$HOME/.vimrc"
#ln -sf "$PWD/plug.vim" "$HOME/.vim/autoload/plug.vim"
