#!/bin/sh
# Codebook:
# Document how you did things so you don't have to reinvent the wheel.
# All notes can be exported as HTML for easy of navigation.

main () {
	# commandline arguments
	LANG=$1
	TITLE=$2

	CBROOT=${CODEBOOK_ROOT:-$HOME/.local/share/codebook}

	# Check for file tree and initialze it if not found
	if [ ! -d "${CBROOT}" ]; then
		CONT="false"
		while [ $CONT = "false" ]
		do
			read -p "Codebook base directory doesn't exist; create it? (y/N) " ANSWER

			case $ANSWER in
				"y"|"Y"|"yes")
					# build file tree
					buildFileTree $CBROOT
					CONT="true"
					;;
				"n"|"N"|"no")
					echo "No base directory found. Exiting..."
					exit 1
					;;
				*)
					echo "${ANSWER} is not a valid response..."
					;;
			esac

		done
	fi
	checkFileTree

	if [ $# -gt 2 ]; then
		usage
		exit 1
	fi
}

# ----------------------------- COMMAND LINE ----------------------------------
# Arguments
# TODO Basic call should be `codebook "lang" "title" (if 2 args then run normally)
# This should create a new markdown file in the proper "lang" directory.  If
# the proper lang/ directory doesn't exist, you should make one.
#
# If only one argument is given then check if it is `build`.  This should cause
# the HTML site to be built and stored in html/site/
# 
# Any other argument should display `usage`
#
# TODO Include support for -h


# Helper Functions

# Checks that important subdirectories exist and creates them if they don't.
checkFileTree () {
	if [ ! -d "${CBROOT}" ]; then
		echo "Codebook root directory does not exist. Exiting..."
		exit 1
	fi
	if [ ! -d "${CBROOT}/lang/" ]; then
		echo "Codebook lang directory does not exist. Creating directory..."
		mkdir ${CBROOT}/lang/
	fi
	if [ ! -d "${CBROOT}/html/" ]; then
		echo "Codebook html directory does not exist. Creating directory..."
		mkdir ${CBROOT}/html/
	fi
	if [ ! -d "${CBROOT}/html/site/" ]; then
		echo "Codebook html/site directory does not exist. Creating directory..."
		mkdir ${CBROOT}/html/site/
	fi
	if [ ! -d "${CBROOT}/html/templates/" ]; then
		echo "Codebook html/templates directory does not exist. Creating directory..."
		mkdir ${CBROOT}/html/templates/
	fi
}

buildFileTree () {
	mkdir $1 $1/lang/ $1/html/ $1/html/templates/	$1/html/site/
}

usage () {
	printf "Usage: codebook [language] [Title]\n"
}

main $@
