#!/bin/sh
# Codebook:
# Document how you did things so you don't have to reinvent the wheel.
# All notes can be exported as HTML for easy of navigation.
# Dependencies:
#		pandoc
main () {
	# commandline arguments
	LANG=$1
	TITLE="${2}"
	#TODO Add support for additional keywords from commandline

	CBROOT=${CODEBOOK_ROOT:-$HOME/.local/share/codebook}

	# Check for file tree and initialze it if not found
	if [ ! -d "${CBROOT}" ]; then
		CONT="false"
		while [ $CONT = "false" ]
		do
			read -p "Codebook base directory doesn't exist; create it? (y/N) " ANSWER

			case $ANSWER in
				"y"|"Y"|"yes")
					# build file tree
					buildFileTree $CBROOT
					CONT="true"
					;;
				"n"|"N"|"no")
					echo "No base directory found. Exiting..."
					exit 1
					;;
				*)
					echo "${ANSWER} is not a valid response..."
					;;
			esac

		done
	fi
	checkFileTree

	# Check for too many or few args
	if [ $# -gt 2 ] || [ $# -eq 0 ]; then
		usage
		echo "$#"
		exit 1
	fi

	# Check if 'build' was selected
	if [ $# -eq 1 ] && [ $LANG = "build" ]; then
		echo "Building site..."
		buildSite
		exit 0
	fi

	# Add any directories and create new .md file
	if [ ! -d "${CBROOT}/lang/${LANG}" ]; then
		echo "Creating directory for ${LANG}"
		mkdir ${CBROOT}/lang/${LANG}/
	fi

	# Remove any spaces from $TITLE
	FILE_TITLE=$(echo "${TITLE}" | sed "s/ /_/g")

	FILE=${CBROOT}/lang/${LANG}/$FILE_TITLE.md # should inline this
	touch "${FILE}"
	echo "Creating ${FILE_TITLE}.md..."

	echo "---" >> "${FILE}"
	echo "title: ${TITLE}" >> "${FILE}"
	echo "keywords: [${LANG}]" >> "${FILE}"
	echo "copywrite: $(date -d +%Y)" >> "${FILE}"
	echo "---" >> "${FILE}"
	
	vi "${FILE}"
}

# ----------------------------- COMMAND LINE ----------------------------------
# TODO Include support for -h
# TODO Refactor commandline parsing to use 'getopts', see man dash(1)

# Helper Functions

# Checks that important subdirectories exist and creates them if they don't.
checkFileTree () {
	if [ ! -d "${CBROOT}" ]; then
		echo "Codebook root directory does not exist. Exiting..."
		exit 1
	fi
	if [ ! -d "${CBROOT}/lang/" ]; then
		echo "Codebook lang directory does not exist. Creating directory..."
		mkdir ${CBROOT}/lang/
	fi
	if [ ! -d "${CBROOT}/html/" ]; then
		echo "Codebook html directory does not exist. Creating directory..."
		mkdir ${CBROOT}/html/
	fi
	if [ ! -d "${CBROOT}/html/site/" ]; then
		echo "Codebook html/site directory does not exist. Creating directory..."
		mkdir ${CBROOT}/html/site/
	fi
	if [ ! -d "${CBROOT}/html/templates/" ]; then
		echo "Codebook html/templates directory does not exist. Creating directory..."
		mkdir ${CBROOT}/html/templates/
	fi
}

buildFileTree () {
	mkdir $1 $1/lang/ $1/html/ $1/html/templates/	$1/html/site/
}

usage () {
	printf "Usage: codebook [language] [Title]\n"
}

buildSite () {
	# loop through all directories in ${CBROOT}/lang and compile all .md files
	# into html. All output should go into ${CBROOT}/html/site
	echo "pandoc --standalone doc.md -o doc.html"
}


main "${@}"
