#!/bin/sh
# add no clobber

src="$SCRIPTS/$1"

if test -e "$src"; then
	printf "Script already exists.\n"
	exit 1
fi

touch "${src}"

if ! test -e "${src}"; then
  printf "Could not create script file. Check privilages.\n"
  exit 1
fi

printf "#!/bin/sh\n" > "${src}"
chmod +x "${src}"
exec vi "+normal G$" "${src}"
