#!/bin/sh
# Check dependencies

if [ -z $(command -v curl) ]; then
  echo "Curl required."
  exit 1
fi

if [ -z $(command -v feh) ]; then
  echo "feh required."
  exit 1
fi

while getopts dho: f
do
  case $f in
  d)
    DLONLY="TRUE" 
    ;;
  h)
    echo "Usage: thisanimedoesnotexist [dh] seed[00000-99999] creativity[0.0-1.0] outputfile[default /tmp/anime.png]"
    echo "-d download picture, don't display."
    echo "-h display this help message."
    exit 0
    ;;
  *)
    echo "Unknown option"
    exit 1
    ;;
  esac
done

SEED="${1:-00001}"
CREATIVITY="${2:-0.5}"
OUTPUTFILE="${3:-/tmp/thisanimedoesnotexist.png}"
URL="https://thisanimedoesnotexist.ai/results/psi-${CREATIVITY}/seed${SEED}.png"
curl "${URL}" > "${OUTPUTFILE}"

if [ -z "${DLONLY}" ]; then
  feh /tmp/anime.png
fi
